# This file contains a list of dependencies that need to be installed

prod: {}
dev:
  bash: scripts.
  findutils: scripts.
  grep: tests.
  xxd: tests.
  git: scripts, tests.
  xxhash: scripts (changeguard).
  rsync: out-of-directory test.
  expect: for `unbuffer`, useful to grab and compare ansi color symbols.
  jq:
    dependency for [yq](https://github.com/kislyuk/yq), which is used to
    generate the README; the README generator needs to use `tomlq` (which is a
    part of `yq`) to query `pyproject.toml`.
  unzip: scripts (pyenv).
  curl: scripts (pyenv).
  git-core: scripts (pyenv).
  gcc: scripts (pyenv).
  make: scripts (pyenv).
  zlib1g-dev: scripts (pyenv).
  libbz2-dev: scripts (pyenv).
  libreadline-dev: scripts (pyenv).
  libsqlite3-dev: scripts (pyenv).
  libssl-dev: scripts (pyenv).
  libffi-dev:
    bdist_wheel (otherwise `pip install .` fails). If installing pyenv, this
    must be installed _first_.
