#!/bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'


TMP_DIR=$(mktemp -d)
ORIGINAL_PWD="${PWD}"

function delete_tmp_dir {
  cd "${ORIGINAL_PWD}"
  rm -rf "${TMP_DIR}"
}
trap delete_tmp_dir EXIT


################################################################################
cat <<EOF > "${TMP_DIR}/EXAMPLE.md.jinja2"

{{ 'TEST' }}
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.generated.md"

OLD
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.expected.md"
<!--

WARNING: This file is auto-generated by snipinator. Do not edit directly.
SOURCE: `EXAMPLE.md.jinja2`.

-->

TEST
EOF

cp "${TMP_DIR}/EXAMPLE.generated.md" "${TMP_DIR}/EXAMPLE.generated.old.md"


python -m snipinator.cli --cwd "${TMP_DIR}" \
  --make-backup \
  -t "${TMP_DIR}/EXAMPLE.md.jinja2" \
  -o "${TMP_DIR}/EXAMPLE.generated.md"

if [ -f "${TMP_DIR}/EXAMPLE.generated.md.bak" ]; then
  echo -e "${GREEN}Successfully created backup file${NC}"
else
  echo -e "${RED}Failed to create backup file${NC}"
  exit 1
fi

# Check the backup.
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.generated.md.bak" \
  "${TMP_DIR}/EXAMPLE.generated.old.md"
echo -e "${GREEN}Backup file matches expected output${NC}"
# Check the contents of the generated file versus the expected output.
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.generated.md" \
  "${TMP_DIR}/EXAMPLE.expected.md"
echo -e "${GREEN}Successfully generated expected output${NC}"
################################################################################

echo -e "${GREEN}${BASH_SOURCE[0]}: All tests passed${NC}"
