#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `snipinator/cli_tests/mv_test.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'


TMP_DIR=$(mktemp -d)
ORIGINAL_PWD="${PWD}"

function delete_tmp_dir {
  cd "${ORIGINAL_PWD}"
  rm -rf "${TMP_DIR}"
}
trap delete_tmp_dir EXIT


################################################################################
cat <<EOF > "${TMP_DIR}/EXAMPLE.md.jinja2"

TEST
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.expected.md"
<!--

WARNING: This file is auto-generated by snipinator. Do not edit directly.
SOURCE: `EXAMPLE.md.jinja2`.

-->

TEST
EOF


################################################################################
# No existing file at destination. Should just work.
python -m snipinator.cli --cwd "${TMP_DIR}" \
  --move \
  -t "${TMP_DIR}/EXAMPLE.md.jinja2" \
  -o "${TMP_DIR}/EXAMPLE.generated.md"

# Check the contents of the generated file versus the expected output
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.expected.md" \
  "${TMP_DIR}/EXAMPLE.generated.md"
echo -e "${GREEN}Successfully generated expected output${NC}"
################################################################################
# Remove all write permissions from the generated file.
chmod a-w "${TMP_DIR}/EXAMPLE.generated.md"
ls -la "${TMP_DIR}/EXAMPLE.generated.md"

################################################################################
python -m snipinator.cli --cwd "${TMP_DIR}" \
  --move \
  -t "${TMP_DIR}/EXAMPLE.md.jinja2" \
  -o "${TMP_DIR}/EXAMPLE.generated.md"

echo -e "${GREEN}Successfully overwrote read-only file${NC}"
################################################################################

echo -e "${GREEN}${BASH_SOURCE[0]}: All tests passed${NC}"
