#!/bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

BLUE='\033[0;34m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

TMP_DIR=$(mktemp -d)


function delete_tmp_dir {
  rm -rf "${TMP_DIR}"
}
trap delete_tmp_dir EXIT


################################################################################
cat <<EOF > "${TMP_DIR}/script.sh"
set +x +v
echo "hi"

echo "DELIM_START"
echo "hello"
echo "DELIM_END"

echo "bye"
EOF

cat <<'EOF' > "${TMP_DIR}/EXAMPLE.md.jinja2"

{{ shell('bash ./script.sh', start='DELIM_START\n', end='\nDELIM_END', backtickify="console", include_args=False) }}
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.expected.md"
<!--

WARNING: This file is auto-generated by snipinator. Do not edit directly.
SOURCE: `EXAMPLE.md.jinja2`.

-->

```console
hello

```
EOF

python -m snipinator.cli --cwd "${TMP_DIR}" \
  -t "${TMP_DIR}/EXAMPLE.md.jinja2" \
  > "${TMP_DIR}/EXAMPLE.generated.md"

# Check the contents of the generated file versus the expected output
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.expected.md" \
  "${TMP_DIR}/EXAMPLE.generated.md"
echo -e "${GREEN}Successfully generated expected output${NC}"
################################################################################
cat <<'EOF' > "${TMP_DIR}/EXAMPLE.shell-snippet-rich.md.jinja2"

{{ shell('bash ./script.sh', start='DELIM_START', end='DELIM_END', backtickify="console", rich="svg", include_args=False) }}

EOF

python -m snipinator.cli --cwd "${TMP_DIR}" \
  -t "${TMP_DIR}/EXAMPLE.shell-snippet-rich.md.jinja2" \
  > "${TMP_DIR}/EXAMPLE.shell-snippet-rich.generated.md"

# Just a smoke test, because we can't easily check an SVG file.

echo -e "${GREEN}Successfully generated expected output${NC}"
################################################################################

echo -e "${GREEN}${BASH_SOURCE[0]}: All tests passed${NC}"
