#!/bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

GREEN='\033[0;32m'
NC='\033[0m'


TMP_DIR=$(mktemp -d)
ORIGINAL_PWD="${PWD}"

function delete_tmp_dir {
  cd "${ORIGINAL_PWD}"
  rm -rf "${TMP_DIR}"
}
trap delete_tmp_dir EXIT


################################################################################
cat <<EOF > "${TMP_DIR}/EXAMPLE.std-warning.md.jinja2"

{{ 'TEST' }}
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.std-warning.expected.md"
<!--

WARNING: This file is auto-generated by snipinator. Do not edit directly.
SOURCE: `EXAMPLE.std-warning.md.jinja2`.

-->

TEST
EOF

python -m snipinator.cli --cwd "${TMP_DIR}" \
  -t "${TMP_DIR}/EXAMPLE.std-warning.md.jinja2" \
  > "${TMP_DIR}/EXAMPLE.std-warning.generated.md"

# Check the contents of the generated file versus the expected output
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.std-warning.expected.md" \
  "${TMP_DIR}/EXAMPLE.std-warning.generated.md"
################################################################################
cat <<EOF > "${TMP_DIR}/EXAMPLE.custom-warning.sh.jinja2"

{{ 'TEST' }}
EOF

cat << 'EOF' > "${TMP_DIR}/EXAMPLE.custom-warning.expected.sh"
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `EXAMPLE.custom-warning.sh.jinja2`.

TEST
EOF

CUSTOM_WARNING=$(cat << 'EOF'
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `{template_file_name}`.
.
EOF
)

python -m snipinator.cli --cwd "${TMP_DIR}" \
  -t "${TMP_DIR}/EXAMPLE.custom-warning.sh.jinja2" \
  --warning-header "${CUSTOM_WARNING%.}" \
  > "${TMP_DIR}/EXAMPLE.custom-warning.generated.sh"

# Check the contents of the generated file versus the expected output
git diff --no-index --exit-code \
  "${TMP_DIR}/EXAMPLE.custom-warning.expected.sh" \
  "${TMP_DIR}/EXAMPLE.custom-warning.generated.sh"
echo -e "${GREEN}Successfully generated expected output${NC}"
################################################################################


echo -e "${GREEN}${BASH_SOURCE[0]}: All tests passed${NC}"
