#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `snipinator/examples/example_example.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail
set +v
PS4="${GREEN}$ ${NC}"

: ECHO_SNIPPET_START
# SNIPPET_START
# View the template file.
cat "snipinator/examples/EXAMPLE.md.jinja2"

python -m snipinator.cli \
  -t "snipinator/examples/EXAMPLE.md.jinja2" \
  --rm \
  --force \
  --create \
  -o "snipinator/examples/EXAMPLE.generated.md" \
  --chmod-ro

# View the generated file.
cat "snipinator/examples/EXAMPLE.generated.md"

# SNIPPET_END
: ECHO_SNIPPET_END
