#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `snipinator/examples/example_example.sh.jinja2`.

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail









  


# SNIPPET_START
docker build -t my-snipinator-image .

docker run --rm --tty \
  -v "${PWD}:/data" \
  my-snipinator-image --help

docker run --rm --tty \
  -v "${PWD}:/data" \
  my-snipinator-image \
  -t "snipinator/examples/EXAMPLE.md.jinja2" \
  --rm \
  --force \
  --create \
  -o "snipinator/examples/EXAMPLE.generated.md" \
  --chmod-ro
# SNIPPET_END
