#!/bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

SCRIPT_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
source "${SCRIPT_DIR}/utilities/common.sh"

VENV_PATH="${PWD}/.cache/scripts/.venv" source "${PROJ_PATH}/scripts/utilities/ensure-venv.sh"
TOML=${PROJ_PATH}/pyproject.toml EXTRA=dev \
  DEV_VENV_PATH="${PWD}/.cache/scripts/.venv" \
  TARGET_VENV_PATH="${PWD}/.cache/scripts/.venv" \
  bash "${PROJ_PATH}/scripts/utilities/ensure-reqs.sh"



CUSTOM_WARNING=$(cat << 'EOF'
#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `{template_file_name}`.

.
EOF
)


python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/cli_tests/mv_test.sh.jinja2" \
  --args '{"mv_args": "--move", "read_only_fail": false}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/cli_tests/mv_test.sh" \
  --chmod-ro


# read_only_fail should be true, but it seems like it might depend on the
# system.
python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/cli_tests/mv_test.sh.jinja2" \
  --args '{"mv_args": "--rm", "read_only_fail": false}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/cli_tests/rm_test.sh" \
  --chmod-ro


python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/cli_tests/mv_test.sh.jinja2" \
  --args '{"mv_args": "--rm --move", "read_only_fail": false}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/cli_tests/rm_mv_test.sh" \
  --chmod-ro
