#!/bin/bash
# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -e -x -v -u -o pipefail

SCRIPT_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
source "${SCRIPT_DIR}/utilities/common.sh"

# NOTE: Use dev requirements to generate the README because the README uses
# shell() with some tools that we only want to install into dev environment.
VENV_PATH="${PWD}/.cache/scripts/.venv" source "${PROJ_PATH}/scripts/utilities/ensure-venv.sh"
TOML=${PROJ_PATH}/pyproject.toml EXTRA=dev \
  DEV_VENV_PATH="${PWD}/.cache/scripts/.venv" \
  TARGET_VENV_PATH="${PWD}/.cache/scripts/.venv" \
  bash "${PROJ_PATH}/scripts/utilities/ensure-reqs.sh"



CUSTOM_WARNING=$(cat << 'EOF'
#!/bin/bash
# WARNING: This file is auto-generated by snipinator. Do not edit directly.
# SOURCE: `{template_file_name}`.

.
EOF
)

python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/examples/example_example.sh.jinja2" \
  --args '{"example_type": "python_module", "module_name": "snipinator.cli"}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/examples/example_example.sh" \
  --chmod-ro


python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/examples/example_example.sh.jinja2" \
  --args '{"example_type": "docker-local", "docker_image_name": "my-snipinator-image"}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/examples/local-docker_example.sh" \
  --chmod-ro


LAST_VERSION=$(tomlq -r -e '.["tool"]["snipinator-project-metadata"]["last_stable_release"]' pyproject.toml)
python -m snipinator.cli \
  -t "${PROJ_PATH}/snipinator/examples/example_example.sh.jinja2" \
  --args '{"example_type": "docker-remote", "docker_image_name": "v'"${LAST_VERSION}"'"}' \
  --warning-header "${CUSTOM_WARNING%.}" \
  --rm \
  --force \
  --create \
  -o "${PROJ_PATH}/snipinator/examples/remote-docker_example-noautorun.sh" \
  --chmod-ro
