name: Generate TOC

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version-file: '.python-version'
    - name: Install Bash (Ubuntu)
      run: sudo apt-get update && sudo apt-get install -y bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run examples
      run: |
        bash scripts/run-all-examples.sh
    - name: Run tests
      run: |
        bash scripts/run-all-tests.sh
